#!/bin/bash
# Configurations that tend to be reset after waking up from sleep,
# thus need to be done when logging in as well as when waking up.

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Change key repeat rate
xset r rate 220 30 && $DIR/zknotify.sh "Key repeat speed adjusted"

$DIR/color-mode.sh normal

# Original mapping is 1 2 3 4 5 6 7 9 2 8
xinput set-button-map 'Kingsis Peripherals Evoluent VerticalMouse 4' 1 2 3 4 5 6 7 0 2 0 && $DIR/zknotify.sh "Disabled navigation buttons for VerticalMouse"
