;;; zk-rangeset.el --- Integer range set library -*- lexical-binding: t; -*-
;;
;; Author: Zhang Kun <zhangkun@google.com> (Generated by Jetski/Gemini)
;;
;; A range set is represented as a list of cons cells: ((begin . end) ...).
;; "begin" is inclusive, "end" is exclusive.
;; The list is sorted by "begin", and has no overlaps or adjacent ranges.

(defun zk-rangeset-add (rangeset range)
  "Add RANGE (begin . end) to RANGESET and return the new rangeset.
If RANGE overlaps or is adjacent to existing ranges, they are merged.
This function is non-destructive to the input RANGESET structure,
although the returned list may share its tail with RANGESET."
  (if (>= (car range) (cdr range))
      rangeset
    (let ((mb (car range))
          (me (cdr range))
          (left nil)
          (rest rangeset)
          (keep-going t)
          curr b-i e-i)
      (while (and rest keep-going)
        (setq curr (car rest))
        (setq b-i (car curr))
        (setq e-i (cdr curr))
        (cond
         ((< e-i mb)
          ;; Current range is strictly before the new range and doesn't touch it.
          (setq left (cons curr left))
          (setq rest (cdr rest)))
         ((> b-i me)
          ;; Current range is strictly after the new range and doesn't touch it.
          ;; Since the list is sorted, we can stop here.
          (setq keep-going nil))
         (t
          ;; Overlap or touch. Merge them.
          (setq mb (min mb b-i))
          (setq me (max me e-i))
          (setq rest (cdr rest)))))
      (nconc (nreverse left) (cons (cons mb me) rest)))))

(provide 'zk-rangeset)
;;; zk-rangeset.el ends here
